# ================================================================
#  Configuracion de conexion a PostgreSQL
#  Este archivo lo lee la clase ConexionBD.java
# ================================================================

# ---- DESARROLLO LOCAL (tu computadora) ----
db.url=jdbc:postgresql://localhost:5432/sistema_solar
db.usuario=postgres
db.clave=postgres

# ---- SERVIDOR DE BASE DE DATOS DE LA UNIVERSIDAD ----
# Cuando vayas a desplegar, COMENTA las 3 lineas de arriba y
# DESCOMENTA estas 3 (quita el # del inicio):
# db.url=jdbc:postgresql://172.17.42.121:5432/sistema_solar
# db.usuario=alumno
# db.clave=1234
